### ISSUE TITLE
Missing config causes an error

### ISSUE THREAD

**Issue by bummzack** [axllent/silverstripe-gfmarkdown#8]
This [line](https://github.com/axllent/silverstripe-gfmarkdown/blob/master/src/FieldTypes/Markdown.php#L26) will cause an error, if no `options` config has been set via YAML. 

I guess it would be a good idea to check if the value has been set, or provide a sensible default-config.

**Comment by axllent** [comment]
Thanks for the report @bummzack - I totally overlooked that! A fix will be coming very shortly.
